# Form implementation generated from reading ui file 'UI_Files/applications_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormApplications(object):
    def setupUi(self, FormApplications):
        FormApplications.setObjectName("FormApplications")
        FormApplications.resize(855, 650)
        FormApplications.setMinimumSize(QtCore.QSize(855, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_Files\\pictures/werhere_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FormApplications.setWindowIcon(icon)
        FormApplications.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.489, y1:1, x2:0.494, y2:0, stop:0 rgba(71, 71, 71, 255), stop:1 rgba(255, 255, 255, 255));")
        self.gridLayout = QtWidgets.QGridLayout(FormApplications)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonPlannedMeetings = QtWidgets.QPushButton(parent=FormApplications)
        self.pushButtonPlannedMeetings.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButtonPlannedMeetings.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonPlannedMeetings.setFont(font)
        self.pushButtonPlannedMeetings.setStyleSheet("QPushButton{\n"
                                                     "    border-radius : 15px;\n"
                                                     "    background-color : rgb(25, 200, 200);\n"
                                                     "    color: rgb(255, 255, 255);\n"
                                                     "}\n"
                                                     "QPushButton:hover{\n"
                                                     "    background-color: rgb(20, 135, 135);\n"
                                                     "    border: 2px solid rgb(162, 0, 0);\n"
                                                     "}")
        self.pushButtonPlannedMeetings.setObjectName("pushButtonPlannedMeetings")
        self.gridLayout.addWidget(self.pushButtonPlannedMeetings, 12, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=FormApplications)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 150))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logo2.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.comboBoxFilterOptions = QtWidgets.QComboBox(parent=FormApplications)
        self.comboBoxFilterOptions.setStyleSheet("border-radius : 15px;\n"
"border: 3px solid rgb(85, 255, 255);\n"
"background-color: rgba(0, 0, 0,55%);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.comboBoxFilterOptions.setObjectName("comboBoxFilterOptions")
        self.gridLayout.addWidget(self.comboBoxFilterOptions, 4, 2, 1, 2)
        self.labelLogo = QtWidgets.QLabel(parent=FormApplications)
        self.labelLogo.setMaximumSize(QtCore.QSize(16777215, 150))
        self.labelLogo.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("UI_Files\\pictures/logo1.ico"))
        self.labelLogo.setObjectName("labelLogo")
        self.gridLayout.addWidget(self.labelLogo, 0, 1, 1, 1)
        self.comboBoxDuplicatedApplications = QtWidgets.QComboBox(parent=FormApplications)
        self.comboBoxDuplicatedApplications.setMinimumSize(QtCore.QSize(0, 35))
        self.comboBoxDuplicatedApplications.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBoxDuplicatedApplications.setStyleSheet("QComboBox{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
                                                          "QComboBox:hover{\n"
                                                          "    border-radius : 15px;\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.comboBoxDuplicatedApplications.setObjectName("comboBoxDuplicatedApplications")
        self.gridLayout.addWidget(self.comboBoxDuplicatedApplications, 14, 0, 1, 1)
        self.pushButtonFilterApplications = QtWidgets.QPushButton(parent=FormApplications)
        self.pushButtonFilterApplications.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButtonFilterApplications.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonFilterApplications.setFont(font)
        self.pushButtonFilterApplications.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
                                                        "QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
                                                        " border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonFilterApplications.setObjectName("pushButtonFilterApplications")
        self.gridLayout.addWidget(self.pushButtonFilterApplications, 17, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.pushButtonExit = QtWidgets.QPushButton(parent=FormApplications)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.gridLayout.addWidget(self.pushButtonExit, 19, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.labelProjectApplications = QtWidgets.QLabel(parent=FormApplications)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelProjectApplications.sizePolicy().hasHeightForWidth())
        self.labelProjectApplications.setSizePolicy(sizePolicy)
        self.labelProjectApplications.setMinimumSize(QtCore.QSize(0, 0))
        self.labelProjectApplications.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        self.labelProjectApplications.setFont(font)
        self.labelProjectApplications.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
                                                    "color: rgb(71, 84, 88);")
        self.labelProjectApplications.setObjectName("labelProjectApplications")
        self.gridLayout.addWidget(self.labelProjectApplications, 1, 2, 1, 1)
        self.pushButtonDifferentialRegistrations = QtWidgets.QPushButton(parent=FormApplications)
        self.pushButtonDifferentialRegistrations.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButtonDifferentialRegistrations.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonDifferentialRegistrations.setFont(font)
        self.pushButtonDifferentialRegistrations.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
" border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonDifferentialRegistrations.setObjectName("pushButtonDifferentialRegistrations")
        self.gridLayout.addWidget(self.pushButtonDifferentialRegistrations, 16, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(parent=FormApplications)
        self.tableWidget.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.gridLayout.addWidget(self.tableWidget, 5, 1, 15, 6)
        self.pushButtonBackMenu = QtWidgets.QPushButton(parent=FormApplications)
        self.pushButtonBackMenu.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButtonBackMenu.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonBackMenu.setFont(font)
        self.pushButtonBackMenu.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
" border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonBackMenu.setObjectName("pushButtonBackMenu")
        self.gridLayout.addWidget(self.pushButtonBackMenu, 18, 0, 1, 1)
        self.labelPicture = QtWidgets.QLabel(parent=FormApplications)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPicture.sizePolicy().hasHeightForWidth())
        self.labelPicture.setSizePolicy(sizePolicy)
        self.labelPicture.setMinimumSize(QtCore.QSize(0, 0))
        self.labelPicture.setMaximumSize(QtCore.QSize(150, 150))
        self.labelPicture.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelPicture.setText("")
        self.labelPicture.setPixmap(QtGui.QPixmap("UI_Files\\pictures/project_app.png"))
        self.labelPicture.setScaledContents(True)
        self.labelPicture.setObjectName("labelPicture")
        self.gridLayout.addWidget(self.labelPicture, 0, 0, 2, 1, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.pushButtonAllPeriods = QtWidgets.QPushButton(parent=FormApplications)
        self.pushButtonAllPeriods.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButtonAllPeriods.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonAllPeriods.setFont(font)
        self.pushButtonAllPeriods.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
                                                "QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonAllPeriods.setObjectName("pushButtonAllPeriods")
        self.gridLayout.addWidget(self.pushButtonAllPeriods, 10, 0, 1, 1)
        self.pushButtonUnscheduledMeeting = QtWidgets.QPushButton(parent=FormApplications)
        self.pushButtonUnscheduledMeeting.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButtonUnscheduledMeeting.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonUnscheduledMeeting.setFont(font)
        self.pushButtonUnscheduledMeeting.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonUnscheduledMeeting.setObjectName("pushButtonUnscheduledMeeting")
        self.gridLayout.addWidget(self.pushButtonUnscheduledMeeting, 13, 0, 1, 1)
        self.lineEditSearch = QtWidgets.QLineEdit(parent=FormApplications)
        self.lineEditSearch.setEnabled(True)
        self.lineEditSearch.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditSearch.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditSearch.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.lineEditSearch.setStyleSheet("QLineEdit {\n"
                                          "  border: 2px solid rgb(38, 38, 48);\n"
                                          "  border-radius: 15px;\n"
                                          "  color: #FFF;\n"
                                          "  padding-left: 15px;\n"
                                          "  background-color: rgba(0, 0, 0,55%);\n"
                                          " \n"
"}\n"
                                          "\n"
                                          "QLineEdit:hover {\n"
                                          "    border: 2px solid rgb(0, 255, 255);\n"
                                          "}\n"
                                          "\n"
                                          " QLineEdit:focus  {\n"
                                          "  border: 2px solid rgb(35, 218, 233);\n"
                                          "  background-color: rgb(47, 47, 47);\n"
                                          "}\n"
                                          "\n"
                                          "   \n"
                                          "\n"
                                          "\n"
                                          "\n"
                                          "")
        self.lineEditSearch.setText("")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.gridLayout.addWidget(self.lineEditSearch, 7, 0, 1, 1)
        self.pushButtonLastPeriod = QtWidgets.QPushButton(parent=FormApplications)
        self.pushButtonLastPeriod.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButtonLastPeriod.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonLastPeriod.setFont(font)
        self.pushButtonLastPeriod.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
                                                "    border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonLastPeriod.setObjectName("pushButtonLastPeriod")
        self.gridLayout.addWidget(self.pushButtonLastPeriod, 9, 0, 1, 1)

        self.retranslateUi(FormApplications)
        QtCore.QMetaObject.connectSlotsByName(FormApplications)
        FormApplications.setTabOrder(self.lineEditSearch, self.pushButtonAllPeriods)
        FormApplications.setTabOrder(self.pushButtonAllPeriods, self.pushButtonPlannedMeetings)
        FormApplications.setTabOrder(self.pushButtonPlannedMeetings, self.pushButtonUnscheduledMeeting)
        FormApplications.setTabOrder(self.pushButtonUnscheduledMeeting, self.pushButtonDifferentialRegistrations)
        FormApplications.setTabOrder(self.pushButtonDifferentialRegistrations, self.pushButtonFilterApplications)
        FormApplications.setTabOrder(self.pushButtonFilterApplications, self.tableWidget)
        FormApplications.setTabOrder(self.tableWidget, self.pushButtonBackMenu)
        FormApplications.setTabOrder(self.pushButtonBackMenu, self.pushButtonExit)

    def retranslateUi(self, FormApplications):
        _translate = QtCore.QCoreApplication.translate
        FormApplications.setWindowTitle(_translate("FormApplications", "APPLICATION"))
        self.pushButtonPlannedMeetings.setText(_translate("FormApplications", "Planned Meetings"))
        self.pushButtonFilterApplications.setText(_translate("FormApplications", "Filter Applications\n"
                                                                                 "(Unique)"))
        self.pushButtonExit.setText(_translate("FormApplications", "Exit"))
        self.labelProjectApplications.setText(_translate("FormApplications", "PROJECT APPLICATIONS"))
        self.pushButtonDifferentialRegistrations.setText(_translate("FormApplications", "Differential Registrations"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FormApplications", "Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FormApplications", "Name Surname"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FormApplications", "Mail"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FormApplications", "Telephone"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("FormApplications", "Post Code"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("FormApplications", "State"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("FormApplications", "Status"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("FormApplications", "Economical \n"
"Situation"))
        self.pushButtonBackMenu.setText(_translate("FormApplications", "Back Menu"))
        self.pushButtonAllPeriods.setText(_translate("FormApplications", "All Periods Applications"))
        self.pushButtonUnscheduledMeeting.setText(_translate("FormApplications", "Unscheduled Meetings"))
        self.lineEditSearch.setPlaceholderText(_translate("FormApplications", "      Name or Surname"))
        self.pushButtonLastPeriod.setText(_translate("FormApplications", "Last Period Applications"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormApplications = QtWidgets.QWidget()
    ui = Ui_FormApplications()
    ui.setupUi(FormApplications)
    FormApplications.show()
    sys.exit(app.exec())
