# Form implementation generated from reading ui file 'UI_Files/candidates_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormCandidates(object):
    def setupUi(self, FormCandidates):
        FormCandidates.setObjectName("FormCandidates")
        FormCandidates.resize(900, 500)
        FormCandidates.setMinimumSize(QtCore.QSize(900, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_Files\\pictures/werhere_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FormCandidates.setWindowIcon(icon)
        FormCandidates.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.489, y1:1, x2:0.494, y2:0, stop:0 rgba(71, 71, 71, 255), stop:1 rgba(255, 255, 255, 255));")
        self.gridLayout = QtWidgets.QGridLayout(FormCandidates)
        self.gridLayout.setObjectName("gridLayout")
        self.labelPicture = QtWidgets.QLabel(parent=FormCandidates)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPicture.sizePolicy().hasHeightForWidth())
        self.labelPicture.setSizePolicy(sizePolicy)
        self.labelPicture.setMaximumSize(QtCore.QSize(150, 150))
        self.labelPicture.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelPicture.setText("")
        self.labelPicture.setPixmap(QtGui.QPixmap("UI_Files\\pictures/mentor_menu.png"))
        self.labelPicture.setScaledContents(True)
        self.labelPicture.setObjectName("labelPicture")
        self.gridLayout.addWidget(self.labelPicture, 0, 0, 3, 1, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lineEditSearch = QtWidgets.QLineEdit(parent=FormCandidates)
        self.lineEditSearch.setEnabled(True)
        self.lineEditSearch.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditSearch.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditSearch.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.lineEditSearch.setStyleSheet("QLineEdit {\n"
"  border: 2px solid rgb(38, 38, 48);\n"
"  border-radius: 15px;\n"
"  color: #FFF;\n"
"  padding-left: 15px;\n"
"  background-color: rgba(0, 0, 0,55%);\n"
" \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 255, 255);\n"
"}\n"
"\n"
" QLineEdit:focus  {\n"
"  border: 2px solid rgb(35, 218, 233);\n"
"  background-color: rgb(47, 47, 47);\n"
"}\n"
"\n"
"   \n"
"\n"
"\n"
"\n"
"")
        self.lineEditSearch.setText("")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.gridLayout.addWidget(self.lineEditSearch, 3, 0, 1, 1)
        self.pushButtonBackMenu = QtWidgets.QPushButton(parent=FormCandidates)
        self.pushButtonBackMenu.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButtonBackMenu.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonBackMenu.setFont(font)
        self.pushButtonBackMenu.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
" border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonBackMenu.setObjectName("pushButtonBackMenu")
        self.gridLayout.addWidget(self.pushButtonBackMenu, 5, 0, 1, 1)
        self.pushButtonGetCandidates = QtWidgets.QPushButton(parent=FormCandidates)
        self.pushButtonGetCandidates.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButtonGetCandidates.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonGetCandidates.setFont(font)
        self.pushButtonGetCandidates.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
" border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonGetCandidates.setObjectName("pushButtonGetCandidates")
        self.gridLayout.addWidget(self.pushButtonGetCandidates, 4, 0, 1, 1)
        self.pushButtonExit = QtWidgets.QPushButton(parent=FormCandidates)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
" border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.gridLayout.addWidget(self.pushButtonExit, 6, 0, 1, 1)
        self.comboBoxFilterOptions = QtWidgets.QComboBox(parent=FormCandidates)
        self.comboBoxFilterOptions.setStyleSheet("border-radius : 15px;\n"
"border: 3px solid rgb(85, 255, 255);\n"
"background-color: rgba(0, 0, 0,55%);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.comboBoxFilterOptions.setObjectName("comboBoxFilterOptions")
        self.gridLayout.addWidget(self.comboBoxFilterOptions, 2, 3, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        self.labelLogo_2 = QtWidgets.QLabel(parent=FormCandidates)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLogo_2.sizePolicy().hasHeightForWidth())
        self.labelLogo_2.setSizePolicy(sizePolicy)
        self.labelLogo_2.setMinimumSize(QtCore.QSize(0, 150))
        self.labelLogo_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.labelLogo_2.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelLogo_2.setText("")
        self.labelLogo_2.setPixmap(QtGui.QPixmap("UI_Files\\pictures/logo1.ico"))
        self.labelLogo_2.setObjectName("labelLogo_2")
        self.gridLayout.addWidget(self.labelLogo_2, 1, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.tableWidget = QtWidgets.QTableWidget(parent=FormCandidates)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.tableWidget.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.gridLayout.addWidget(self.tableWidget, 3, 1, 5, 5)
        self.label = QtWidgets.QLabel(parent=FormCandidates)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 150))
        self.label.setMaximumSize(QtCore.QSize(16777215, 150))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logo2.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 2)
        self.labelCandidates = QtWidgets.QLabel(parent=FormCandidates)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        self.labelCandidates.setFont(font)
        self.labelCandidates.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"color: rgb(71, 84, 88);")
        self.labelCandidates.setObjectName("labelCandidates")
        self.gridLayout.addWidget(self.labelCandidates, 2, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)

        self.retranslateUi(FormCandidates)
        QtCore.QMetaObject.connectSlotsByName(FormCandidates)
        FormCandidates.setTabOrder(self.lineEditSearch, self.pushButtonGetCandidates)
        FormCandidates.setTabOrder(self.pushButtonGetCandidates, self.tableWidget)
        FormCandidates.setTabOrder(self.tableWidget, self.comboBoxFilterOptions)
        FormCandidates.setTabOrder(self.comboBoxFilterOptions, self.pushButtonBackMenu)
        FormCandidates.setTabOrder(self.pushButtonBackMenu, self.pushButtonExit)

    def retranslateUi(self, FormCandidates):
        _translate = QtCore.QCoreApplication.translate
        FormCandidates.setWindowTitle(_translate("FormCandidates", "CANDIDATES MENU"))
        self.lineEditSearch.setPlaceholderText(_translate("FormCandidates", "      Name or Surname"))
        self.pushButtonBackMenu.setText(_translate("FormCandidates", "Back Menu"))
        self.pushButtonGetCandidates.setText(_translate("FormCandidates", "Get Candidates"))
        self.pushButtonExit.setText(_translate("FormCandidates", "Exit"))
        self.labelCandidates.setText(_translate("FormCandidates", "CANDIDATES MENU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormCandidates = QtWidgets.QWidget()
    ui = Ui_FormCandidates()
    ui.setupUi(FormCandidates)
    FormCandidates.show()
    sys.exit(app.exec())
