# Form implementation generated from reading ui file 'UI_Files/interviews_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormInterviews(object):
    def setupUi(self, FormInterviews):
        FormInterviews.setObjectName("FormInterviews")
        FormInterviews.resize(840, 500)
        FormInterviews.setMinimumSize(QtCore.QSize(840, 500))
        FormInterviews.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_Files\\pictures/logo1.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FormInterviews.setWindowIcon(icon)
        FormInterviews.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.489, y1:1, x2:0.494, y2:0, stop:0 rgba(71, 71, 71, 255), stop:1 rgba(255, 255, 255, 255));")
        self.gridLayout = QtWidgets.QGridLayout(FormInterviews)
        self.gridLayout.setObjectName("gridLayout")
        self.labelLogo = QtWidgets.QLabel(parent=FormInterviews)
        self.labelLogo.setMaximumSize(QtCore.QSize(16777215, 150))
        self.labelLogo.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("UI_Files\\pictures/logo1.ico"))
        self.labelLogo.setScaledContents(False)
        self.labelLogo.setObjectName("labelLogo")
        self.gridLayout.addWidget(self.labelLogo, 0, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.tableWidget = QtWidgets.QTableWidget(parent=FormInterviews)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(170)
        self.gridLayout.addWidget(self.tableWidget, 3, 1, 6, 3)
        self.comboBoxAssignedApplicants = QtWidgets.QComboBox(parent=FormInterviews)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxAssignedApplicants.sizePolicy().hasHeightForWidth())
        self.comboBoxAssignedApplicants.setSizePolicy(sizePolicy)
        self.comboBoxAssignedApplicants.setMinimumSize(QtCore.QSize(150, 35))
        self.comboBoxAssignedApplicants.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        self.comboBoxAssignedApplicants.setFont(font)
        self.comboBoxAssignedApplicants.setStyleSheet("QComboBox {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 1px 18px 1px 3px; /* Doldurma ayarları */\n"
"}\n"
"\n"
"QComboBox:placeholder {\n"
"    padding-left: 10px; /* Soldan boşluk */\n"
"    padding-right: 10px; /* Sağdan boşluk */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none; /* Açılır ok kutusu sınırını kaldır */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(/path/to/your/image.png); /* İsteğe bağlı olarak, kendi ok resminizi kullanabilirsiniz */\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* Sınır sol kısmını kaldırabilirsiniz */\n"
"    border-top-right-radius: 3px; /* Açılır ok kutusu köşelerini ayarlayın */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    background-color: rgb(25, 200, 200); /* Açılan öğelerin arka plan rengi */\n"
"    color: rgb(255, 255, 255); /* Açılan öğelerin metin rengi */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgb(20, 135, 135); /* Açılan öğelerin üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid darkgray;\n"
"    selection-background-color: rgb(20, 135, 135);\n"
"    background-color: rgb(25, 200, 200); /* Açılan liste arka plan rengi */\n"
"    border-radius: 15px; /* Açılan liste köşe yuvarlama */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(162, 0, 0);\n"
"}\n"
"")
        self.comboBoxAssignedApplicants.setObjectName("comboBoxAssignedApplicants")
        self.gridLayout.addWidget(self.comboBoxAssignedApplicants, 5, 0, 1, 1)
        self.labelPicture = QtWidgets.QLabel(parent=FormInterviews)
        self.labelPicture.setMaximumSize(QtCore.QSize(150, 150))
        self.labelPicture.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelPicture.setText("")
        self.labelPicture.setPixmap(QtGui.QPixmap("UI_Files\\pictures/interviews_menu.png"))
        self.labelPicture.setScaledContents(True)
        self.labelPicture.setObjectName("labelPicture")
        self.gridLayout.addWidget(self.labelPicture, 0, 0, 1, 1)
        self.lineEditSearch = QtWidgets.QLineEdit(parent=FormInterviews)
        self.lineEditSearch.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSearch.sizePolicy().hasHeightForWidth())
        self.lineEditSearch.setSizePolicy(sizePolicy)
        self.lineEditSearch.setMinimumSize(QtCore.QSize(150, 35))
        self.lineEditSearch.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditSearch.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.lineEditSearch.setStyleSheet("QLineEdit {\n"
"  border: 2px solid rgb(38, 38, 48);\n"
"  border-radius: 15px;\n"
"  color: #FFF;\n"
"  padding-left: 15px;\n"
"  background-color: rgba(0, 0, 0,55%);\n"
" \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 255, 255);\n"
"}\n"
"\n"
" QLineEdit:focus  {\n"
"  border: 2px solid rgb(35, 218, 233);\n"
"  background-color: rgb(47, 47, 47);\n"
"}\n"
"\n"
"   \n"
"\n"
"\n"
"\n"
"")
        self.lineEditSearch.setText("")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.gridLayout.addWidget(self.lineEditSearch, 3, 0, 1, 1)
        self.pushButtonUnassignedApllicants = QtWidgets.QPushButton(parent=FormInterviews)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonUnassignedApllicants.sizePolicy().hasHeightForWidth())
        self.pushButtonUnassignedApllicants.setSizePolicy(sizePolicy)
        self.pushButtonUnassignedApllicants.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButtonUnassignedApllicants.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.pushButtonUnassignedApllicants.setFont(font)
        self.pushButtonUnassignedApllicants.setAccessibleDescription("")
        self.pushButtonUnassignedApllicants.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
" border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonUnassignedApllicants.setObjectName("pushButtonUnassignedApllicants")
        self.gridLayout.addWidget(self.pushButtonUnassignedApllicants, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.labelMenu = QtWidgets.QLabel(parent=FormInterviews)
        self.labelMenu.setMinimumSize(QtCore.QSize(300, 0))
        self.labelMenu.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        self.labelMenu.setFont(font)
        self.labelMenu.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"color: rgb(71, 84, 88);")
        self.labelMenu.setScaledContents(True)
        self.labelMenu.setWordWrap(True)
        self.labelMenu.setObjectName("labelMenu")
        self.gridLayout.addWidget(self.labelMenu, 1, 2, 1, 1)
        self.pushButtonBackMenu = QtWidgets.QPushButton(parent=FormInterviews)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBackMenu.sizePolicy().hasHeightForWidth())
        self.pushButtonBackMenu.setSizePolicy(sizePolicy)
        self.pushButtonBackMenu.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButtonBackMenu.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonBackMenu.setFont(font)
        self.pushButtonBackMenu.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
" border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonBackMenu.setObjectName("pushButtonBackMenu")
        self.gridLayout.addWidget(self.pushButtonBackMenu, 6, 0, 1, 1)
        self.pushButtonExit = QtWidgets.QPushButton(parent=FormInterviews)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonExit.sizePolicy().hasHeightForWidth())
        self.pushButtonExit.setSizePolicy(sizePolicy)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
" border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.gridLayout.addWidget(self.pushButtonExit, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=FormInterviews)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 150))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("UI_Files\\pictures/logo2.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1, QtCore.Qt.AlignmentFlag.AlignTop)
        self.lineEditSearch.raise_()
        self.labelMenu.raise_()
        self.labelPicture.raise_()
        self.labelLogo.raise_()
        self.pushButtonExit.raise_()
        self.pushButtonUnassignedApllicants.raise_()
        self.pushButtonBackMenu.raise_()
        self.tableWidget.raise_()
        self.label.raise_()
        self.comboBoxAssignedApplicants.raise_()

        self.retranslateUi(FormInterviews)
        QtCore.QMetaObject.connectSlotsByName(FormInterviews)

    def retranslateUi(self, FormInterviews):
        _translate = QtCore.QCoreApplication.translate
        FormInterviews.setWindowTitle(_translate("FormInterviews", "INTERVIEWS"))
        self.comboBoxAssignedApplicants.setPlaceholderText(_translate("FormInterviews", "Assigned Applicants"))
        self.lineEditSearch.setPlaceholderText(_translate("FormInterviews", "      Name or Surname"))
        self.pushButtonUnassignedApllicants.setText(_translate("FormInterviews", "Unassigned Apllicants"))
        self.labelMenu.setText(_translate("FormInterviews", "INTERVIEWS MENU"))
        self.pushButtonBackMenu.setText(_translate("FormInterviews", "Back Menu"))
        self.pushButtonExit.setText(_translate("FormInterviews", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormInterviews = QtWidgets.QWidget()
    ui = Ui_FormInterviews()
    ui.setupUi(FormInterviews)
    FormInterviews.show()
    sys.exit(app.exec())
