# Form implementation generated from reading ui file 'UI_Files/management_ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormManagement(object):
    def setupUi(self, FormManagement):
        FormManagement.setObjectName("FormManagement")
        FormManagement.resize(836, 461)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FormManagement.sizePolicy().hasHeightForWidth())
        FormManagement.setSizePolicy(sizePolicy)
        FormManagement.setMinimumSize(QtCore.QSize(0, 0))
        FormManagement.setMaximumSize(QtCore.QSize(65000, 65000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_Files\\pictures/werhere_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FormManagement.setWindowIcon(icon)
        FormManagement.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.489, y1:1, x2:0.494, y2:0, stop:0 rgba(71, 71, 71, 255), stop:1 rgba(255, 255, 255, 255));")
        self.gridLayout = QtWidgets.QGridLayout(FormManagement)
        self.gridLayout.setObjectName("gridLayout")
        self.labelManagement = QtWidgets.QLabel(parent=FormManagement)
        self.labelManagement.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.labelManagement.setFont(font)
        self.labelManagement.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"color: rgb(71, 84, 88);")
        self.labelManagement.setObjectName("labelManagement")
        self.gridLayout.addWidget(self.labelManagement, 1, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelLogo = QtWidgets.QLabel(parent=FormManagement)
        self.labelLogo.setMinimumSize(QtCore.QSize(0, 150))
        self.labelLogo.setMaximumSize(QtCore.QSize(16777215, 150))
        self.labelLogo.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("UI_Files\\pictures/logo1.ico"))
        self.labelLogo.setObjectName("labelLogo")
        self.gridLayout.addWidget(self.labelLogo, 0, 1, 1, 2)
        self.pushButtonGetAllEvents = QtWidgets.QPushButton(parent=FormManagement)
        self.pushButtonGetAllEvents.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonGetAllEvents.setFont(font)
        self.pushButtonGetAllEvents.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
" border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonGetAllEvents.setObjectName("pushButtonGetAllEvents")
        self.gridLayout.addWidget(self.pushButtonGetAllEvents, 4, 0, 1, 1)
        self.pushButtonSendEmail = QtWidgets.QPushButton(parent=FormManagement)
        self.pushButtonSendEmail.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSendEmail.setFont(font)
        self.pushButtonSendEmail.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
" border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonSendEmail.setObjectName("pushButtonSendEmail")
        self.gridLayout.addWidget(self.pushButtonSendEmail, 5, 0, 1, 1)
        self.pushButtonBackMenu = QtWidgets.QPushButton(parent=FormManagement)
        self.pushButtonBackMenu.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBackMenu.setFont(font)
        self.pushButtonBackMenu.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
" border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonBackMenu.setObjectName("pushButtonBackMenu")
        self.gridLayout.addWidget(self.pushButtonBackMenu, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=FormManagement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 150))
        self.label.setMaximumSize(QtCore.QSize(16777215, 150))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logo2.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.pushButtonExit = QtWidgets.QPushButton(parent=FormManagement)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
" border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.gridLayout.addWidget(self.pushButtonExit, 7, 0, 1, 1)
        self.labelPicture = QtWidgets.QLabel(parent=FormManagement)
        self.labelPicture.setMinimumSize(QtCore.QSize(0, 150))
        self.labelPicture.setMaximumSize(QtCore.QSize(150, 150))
        self.labelPicture.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelPicture.setText("")
        self.labelPicture.setPixmap(QtGui.QPixmap("UI_Files\\pictures/main_admin.png"))
        self.labelPicture.setScaledContents(True)
        self.labelPicture.setObjectName("labelPicture")
        self.gridLayout.addWidget(self.labelPicture, 0, 0, 2, 1, QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(parent=FormManagement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.gridLayout.addWidget(self.tableWidget, 3, 1, 6, 4)

        self.retranslateUi(FormManagement)
        QtCore.QMetaObject.connectSlotsByName(FormManagement)
        FormManagement.setTabOrder(self.pushButtonGetAllEvents, self.pushButtonSendEmail)
        FormManagement.setTabOrder(self.pushButtonSendEmail, self.pushButtonBackMenu)
        FormManagement.setTabOrder(self.pushButtonBackMenu, self.tableWidget)
        FormManagement.setTabOrder(self.tableWidget, self.pushButtonExit)

    def retranslateUi(self, FormManagement):
        _translate = QtCore.QCoreApplication.translate
        FormManagement.setWindowTitle(_translate("FormManagement", "MANAGEMENT PAGE"))
        self.labelManagement.setText(_translate("FormManagement", "MANAGEMENT PAGE"))
        self.pushButtonGetAllEvents.setText(_translate("FormManagement", "Get All Events"))
        self.pushButtonSendEmail.setText(_translate("FormManagement", "Send Mail"))
        self.pushButtonBackMenu.setText(_translate("FormManagement", "Back Menu"))
        self.pushButtonExit.setText(_translate("FormManagement", "Exit"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FormManagement", "Event Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FormManagement", "Start Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FormManagement", "Participant Mail"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FormManagement", "Organizer Mail"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormManagement = QtWidgets.QWidget()
    ui = Ui_FormManagement()
    ui.setupUi(FormManagement)
    FormManagement.show()
    sys.exit(app.exec())
