# Form implementation generated from reading ui file 'UI_Files/add_new_user_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogAddNewUser(object):
    def setupUi(self, DialogAddNewUser):
        DialogAddNewUser.setObjectName("DialogAddNewUser")
        DialogAddNewUser.resize(604, 410)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_Files\\pictures/logo_organization1.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        DialogAddNewUser.setWindowIcon(icon)
        DialogAddNewUser.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.489, y1:1, x2:0.494, y2:0, stop:0 rgba(71, 71, 71, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"QToolTip { background-color: yellow; color: black; border: 1px solid black;}")
        self.frameAddNewUser = QtWidgets.QFrame(parent=DialogAddNewUser)
        self.frameAddNewUser.setGeometry(QtCore.QRect(250, 0, 351, 411))
        self.frameAddNewUser.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameAddNewUser.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameAddNewUser.setObjectName("frameAddNewUser")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameAddNewUser)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelLogo = QtWidgets.QLabel(parent=self.frameAddNewUser)
        self.labelLogo.setMinimumSize(QtCore.QSize(331, 70))
        self.labelLogo.setMaximumSize(QtCore.QSize(331, 70))
        self.labelLogo.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.labelLogo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("UI_Files\\pictures/logo_organization2.png"))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setObjectName("labelLogo")
        self.verticalLayout_2.addWidget(self.labelLogo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.labelCaseName = QtWidgets.QLabel(parent=self.frameAddNewUser)
        self.labelCaseName.setMinimumSize(QtCore.QSize(330, 0))
        self.labelCaseName.setMaximumSize(QtCore.QSize(330, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        self.labelCaseName.setFont(font)
        self.labelCaseName.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.labelCaseName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelCaseName.setObjectName("labelCaseName")
        self.verticalLayout_2.addWidget(self.labelCaseName)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(parent=self.frameAddNewUser)
        self.line.setMaximumSize(QtCore.QSize(330, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelUserName = QtWidgets.QLabel(parent=self.frameAddNewUser)
        self.labelUserName.setMaximumSize(QtCore.QSize(70, 16777215))
        self.labelUserName.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.labelUserName.setObjectName("labelUserName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelUserName)
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.frameAddNewUser)
        self.lineEditUsername.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEditUsername.setMaximumSize(QtCore.QSize(220, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditUsername.setFont(font)
        self.lineEditUsername.setStyleSheet("QLineEdit {\n"
"    color: darkRed;\n"
"    background-color: rgb(253, 255, 230);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}\n"
"\n"
"QLineEdit:focus  {\n"
"  border: 2px solid rgb(162, 0, 0);\n"
"}\n"
"\n"
"\n"
"QToolTip {\n"
"     border-radius: 15px;\n"
"    background-color: yellow; \n"
"    color: black; \n"
"    border: 1px solid black;\n"
"}")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditUsername)
        self.labelAuthority = QtWidgets.QLabel(parent=self.frameAddNewUser)
        self.labelAuthority.setMaximumSize(QtCore.QSize(70, 16777215))
        self.labelAuthority.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.labelAuthority.setObjectName("labelAuthority")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelAuthority)
        self.comboBoxAuthority = QtWidgets.QComboBox(parent=self.frameAddNewUser)
        self.comboBoxAuthority.setMinimumSize(QtCore.QSize(220, 25))
        self.comboBoxAuthority.setMaximumSize(QtCore.QSize(220, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxAuthority.setFont(font)
        self.comboBoxAuthority.setStyleSheet("QComboBox {\n"
"    color: darkRed;\n"
"    border-radius: 5px;\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"QComboBox:placeholder {\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border-top-left-radius: 3px;\n"
"    border-bottom-left-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(255, 80, 0);\n"
"    selection-background-color: rgb(245, 245, 245);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid rgb(255, 80, 0); /* Hover ile kenar çizgisi ekleniyor */\n"
"}\n"
"\n"
"QComboBox:focus  {\n"
"  border: 2px solid rgb(162, 0, 0);\n"
"}\n"
"\n"
"QToolTip {\n"
"     border-radius: 15px;\n"
"    background-color: yellow; \n"
"    color: black; \n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.comboBoxAuthority.setObjectName("comboBoxAuthority")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBoxAuthority)
        self.labelName = QtWidgets.QLabel(parent=self.frameAddNewUser)
        self.labelName.setMaximumSize(QtCore.QSize(70, 16777215))
        self.labelName.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.labelName.setObjectName("labelName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelName)
        self.lineEditName = QtWidgets.QLineEdit(parent=self.frameAddNewUser)
        self.lineEditName.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEditName.setMaximumSize(QtCore.QSize(220, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditName.setFont(font)
        self.lineEditName.setStyleSheet("QLineEdit {\n"
"    color: darkRed;\n"
"    background-color: rgb(253, 255, 230);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}\n"
"\n"
"QLineEdit:focus  {\n"
"  border: 2px solid rgb(162, 0, 0);\n"
"}\n"
"\n"
"\n"
"QToolTip {\n"
"     border-radius: 15px;\n"
"    background-color: yellow; \n"
"    color: black; \n"
"    border: 1px solid black;\n"
"}")
        self.lineEditName.setObjectName("lineEditName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditName)
        self.labelSurname = QtWidgets.QLabel(parent=self.frameAddNewUser)
        self.labelSurname.setMaximumSize(QtCore.QSize(70, 16777215))
        self.labelSurname.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.labelSurname.setObjectName("labelSurname")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelSurname)
        self.lineEditSurname = QtWidgets.QLineEdit(parent=self.frameAddNewUser)
        self.lineEditSurname.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEditSurname.setMaximumSize(QtCore.QSize(220, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditSurname.setFont(font)
        self.lineEditSurname.setStyleSheet("QLineEdit {\n"
"    color: darkRed;\n"
"    background-color: rgb(253, 255, 230);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}\n"
"\n"
"QLineEdit:focus  {\n"
"  border: 2px solid rgb(162, 0, 0);\n"
"}\n"
"\n"
"\n"
"QToolTip {\n"
"     border-radius: 15px;\n"
"    background-color: yellow; \n"
"    color: black; \n"
"    border: 1px solid black;\n"
"}")
        self.lineEditSurname.setObjectName("lineEditSurname")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditSurname)
        self.labelPassword = QtWidgets.QLabel(parent=self.frameAddNewUser)
        self.labelPassword.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.frameAddNewUser)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEditPassword.setMaximumSize(QtCore.QSize(220, 25))
        self.lineEditPassword.setStyleSheet("QLineEdit {\n"
"    color: darkRed;\n"
"    background-color: rgb(253, 255, 230);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}\n"
"\n"
"QLineEdit:focus  {\n"
"  border: 2px solid rgb(162, 0, 0);\n"
"}\n"
"\n"
"\n"
"QToolTip {\n"
"     border-radius: 15px;\n"
"    background-color: yellow; \n"
"    color: black; \n"
"    border: 1px solid black;\n"
"}")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditPassword)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridFrameNUAApproveCancel = QtWidgets.QFrame(parent=self.frameAddNewUser)
        self.gridFrameNUAApproveCancel.setStyleSheet("background-color: rgb(0, 0, 0, 255);")
        self.gridFrameNUAApproveCancel.setObjectName("gridFrameNUAApproveCancel")
        self.formLayout_4 = QtWidgets.QFormLayout(self.gridFrameNUAApproveCancel)
        self.formLayout_4.setObjectName("formLayout_4")
        self.pushButtonNUAApprove = QtWidgets.QPushButton(parent=self.gridFrameNUAApproveCancel)
        self.pushButtonNUAApprove.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButtonNUAApprove.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonNUAApprove.setMouseTracking(True)
        self.pushButtonNUAApprove.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButtonNUAApprove.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}\n"
"\n"
"QPushButton:focus  {\n"
"  border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonNUAApprove.setObjectName("pushButtonNUAApprove")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.pushButtonNUAApprove)
        self.pushButtonNUACancel = QtWidgets.QPushButton(parent=self.gridFrameNUAApproveCancel)
        self.pushButtonNUACancel.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButtonNUACancel.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonNUACancel.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}\n"
"\n"
"QPushButton:focus  {\n"
"  border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonNUACancel.setObjectName("pushButtonNUACancel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButtonNUACancel)
        self.verticalLayout_2.addWidget(self.gridFrameNUAApproveCancel)
        self.labelAddNewUserIco = QtWidgets.QLabel(parent=DialogAddNewUser)
        self.labelAddNewUserIco.setGeometry(QtCore.QRect(45, 230, 141, 141))
        self.labelAddNewUserIco.setMinimumSize(QtCore.QSize(100, 100))
        self.labelAddNewUserIco.setMaximumSize(QtCore.QSize(200, 200))
        self.labelAddNewUserIco.setStyleSheet("QLabel { background-color: rgb(0, 0, 0, 0); }")
        self.labelAddNewUserIco.setText("")
        self.labelAddNewUserIco.setPixmap(QtGui.QPixmap("UI_Files\\pictures/icon_add_new_user.png"))
        self.labelAddNewUserIco.setScaledContents(True)
        self.labelAddNewUserIco.setObjectName("labelAddNewUserIco")
        self.frameYellowSide = QtWidgets.QFrame(parent=DialogAddNewUser)
        self.frameYellowSide.setGeometry(QtCore.QRect(-20, -10, 251, 421))
        self.frameYellowSide.setStyleSheet("QFrame {\n"
"    background-color: rgb(254, 213, 1);\n"
"}")
        self.frameYellowSide.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameYellowSide.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameYellowSide.setObjectName("frameYellowSide")
        self.labelUserImage = QtWidgets.QLabel(parent=self.frameYellowSide)
        self.labelUserImage.setGeometry(QtCore.QRect(30, 20, 210, 210))
        self.labelUserImage.setMaximumSize(QtCore.QSize(250, 250))
        self.labelUserImage.setStyleSheet("QLabel { background-color: rgb(0, 0, 0, 0); }")
        self.labelUserImage.setText("")
        self.labelUserImage.setPixmap(QtGui.QPixmap("UI_Files\\pictures/pic_user.png"))
        self.labelUserImage.setScaledContents(True)
        self.labelUserImage.setObjectName("labelUserImage")
        self.frameAddNewUser.raise_()
        self.frameYellowSide.raise_()
        self.labelAddNewUserIco.raise_()

        self.retranslateUi(DialogAddNewUser)
        QtCore.QMetaObject.connectSlotsByName(DialogAddNewUser)
        DialogAddNewUser.setTabOrder(self.pushButtonNUAApprove, self.pushButtonNUACancel)
        DialogAddNewUser.setTabOrder(self.pushButtonNUACancel, self.lineEditUsername)
        DialogAddNewUser.setTabOrder(self.lineEditUsername, self.lineEditPassword)
        DialogAddNewUser.setTabOrder(self.lineEditPassword, self.comboBoxAuthority)
        DialogAddNewUser.setTabOrder(self.comboBoxAuthority, self.lineEditName)
        DialogAddNewUser.setTabOrder(self.lineEditName, self.lineEditSurname)

    def retranslateUi(self, DialogAddNewUser):
        _translate = QtCore.QCoreApplication.translate
        DialogAddNewUser.setWindowTitle(_translate("DialogAddNewUser", "Add New User"))
        self.labelCaseName.setText(_translate("DialogAddNewUser", "New Account Adding Menu"))
        self.labelUserName.setText(_translate("DialogAddNewUser", "UserName :"))
        self.labelAuthority.setText(_translate("DialogAddNewUser", "Authority   :"))
        self.labelName.setText(_translate("DialogAddNewUser", "Name        :"))
        self.labelSurname.setText(_translate("DialogAddNewUser", "Surname   :"))
        self.labelPassword.setText(_translate("DialogAddNewUser", "Password   :"))
        self.pushButtonNUAApprove.setText(_translate("DialogAddNewUser", "APPROVE"))
        self.pushButtonNUACancel.setText(_translate("DialogAddNewUser", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAddNewUser = QtWidgets.QDialog()
    ui = Ui_DialogAddNewUser()
    ui.setupUi(DialogAddNewUser)
    DialogAddNewUser.show()
    sys.exit(app.exec())
