# Form implementation generated from reading ui file 'UI_Files/interviews_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormInterviews(object):
    def setupUi(self, FormInterviews):
        FormInterviews.setObjectName("FormInterviews")
        FormInterviews.resize(890, 525)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FormInterviews.sizePolicy().hasHeightForWidth())
        FormInterviews.setSizePolicy(sizePolicy)
        FormInterviews.setMinimumSize(QtCore.QSize(835, 525))
        font = QtGui.QFont()
        font.setPointSize(7)
        FormInterviews.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_Files\\pictures/logo_organization1.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FormInterviews.setWindowIcon(icon)
        FormInterviews.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.489, y1:1, x2:0.494, y2:0, stop:0 rgba(71, 71, 71, 255), stop:1 rgba(255, 255, 255, 255));")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FormInterviews)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelPicture = QtWidgets.QLabel(parent=FormInterviews)
        self.labelPicture.setMinimumSize(QtCore.QSize(150, 130))
        self.labelPicture.setMaximumSize(QtCore.QSize(150, 130))
        self.labelPicture.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelPicture.setText("")
        self.labelPicture.setPixmap(QtGui.QPixmap("UI_Files\\pictures/menu_interviews.png"))
        self.labelPicture.setScaledContents(True)
        self.labelPicture.setObjectName("labelPicture")
        self.horizontalLayout.addWidget(self.labelPicture)
        self.labelLogo = QtWidgets.QLabel(parent=FormInterviews)
        self.labelLogo.setMinimumSize(QtCore.QSize(130, 140))
        self.labelLogo.setMaximumSize(QtCore.QSize(130, 140))
        self.labelLogo.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("UI_Files\\pictures/logo_organization1.ico"))
        self.labelLogo.setObjectName("labelLogo")
        self.horizontalLayout.addWidget(self.labelLogo)
        self.label = QtWidgets.QLabel(parent=FormInterviews)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(522, 110))
        self.label.setMaximumSize(QtCore.QSize(522, 110))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("UI_Files\\pictures/logo_organization2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelAreaKeeper1 = QtWidgets.QLabel(parent=FormInterviews)
        self.labelAreaKeeper1.setMinimumSize(QtCore.QSize(190, 40))
        self.labelAreaKeeper1.setMaximumSize(QtCore.QSize(190, 40))
        self.labelAreaKeeper1.setStyleSheet("QLabel {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.labelAreaKeeper1.setText("")
        self.labelAreaKeeper1.setObjectName("labelAreaKeeper1")
        self.horizontalLayout_2.addWidget(self.labelAreaKeeper1)
        self.labelMenu = QtWidgets.QLabel(parent=FormInterviews)
        self.labelMenu.setMinimumSize(QtCore.QSize(350, 40))
        self.labelMenu.setMaximumSize(QtCore.QSize(350, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(22)
        font.setBold(True)
        self.labelMenu.setFont(font)
        self.labelMenu.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"color: rgb(71, 84, 88);")
        self.labelMenu.setScaledContents(True)
        self.labelMenu.setObjectName("labelMenu")
        self.horizontalLayout_2.addWidget(self.labelMenu)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.comboBoxFilterOptions = QtWidgets.QComboBox(parent=FormInterviews)
        self.comboBoxFilterOptions.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBoxFilterOptions.setStyleSheet("QComboBox {\n"
"    border-radius : 15px;\n"
"    border: 3px solid rgb(85, 255, 255);\n"
"    background-color: rgba(0, 0, 0,55%);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}\n"
"\n"
"QComboBox:focus  {\n"
"  border: 2px solid rgb(162, 0, 0);\n"
"  background-color: rgb(47, 47, 47);\n"
"}\n"
"")
        self.comboBoxFilterOptions.setObjectName("comboBoxFilterOptions")
        self.horizontalLayout_2.addWidget(self.comboBoxFilterOptions)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=FormInterviews)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 1, 1, 1)
        self.frameButtons = QtWidgets.QFrame(parent=FormInterviews)
        self.frameButtons.setMinimumSize(QtCore.QSize(190, 290))
        self.frameButtons.setMaximumSize(QtCore.QSize(190, 16777215))
        self.frameButtons.setStyleSheet("QFrame {\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.frameButtons.setObjectName("frameButtons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameButtons)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.frameButtons)
        self.lineEditSearch.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSearch.sizePolicy().hasHeightForWidth())
        self.lineEditSearch.setSizePolicy(sizePolicy)
        self.lineEditSearch.setMinimumSize(QtCore.QSize(170, 35))
        self.lineEditSearch.setMaximumSize(QtCore.QSize(170, 35))
        self.lineEditSearch.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.lineEditSearch.setStyleSheet("QLineEdit {\n"
"  border: 2px solid rgb(35, 218, 233);\n"
"  border-radius: 15px;\n"
"  color: #FFF;\n"
"  padding-left: 15px;\n"
"  background-color: rgba(0, 0, 0,55%); \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}\n"
"\n"
"QLineEdit:focus  {\n"
"  border: 2px solid rgb(162, 0, 0);\n"
"  background-color: rgb(47, 47, 47);\n"
"}\n"
"")
        self.lineEditSearch.setText("")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.verticalLayout.addWidget(self.lineEditSearch)
        self.pushButtonUnassignedApplicants = QtWidgets.QPushButton(parent=self.frameButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonUnassignedApplicants.sizePolicy().hasHeightForWidth())
        self.pushButtonUnassignedApplicants.setSizePolicy(sizePolicy)
        self.pushButtonUnassignedApplicants.setMinimumSize(QtCore.QSize(170, 35))
        self.pushButtonUnassignedApplicants.setMaximumSize(QtCore.QSize(170, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonUnassignedApplicants.setFont(font)
        self.pushButtonUnassignedApplicants.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}")
        self.pushButtonUnassignedApplicants.setObjectName("pushButtonUnassignedApplicants")
        self.verticalLayout.addWidget(self.pushButtonUnassignedApplicants)
        self.pushButtonAssignedApplicants = QtWidgets.QPushButton(parent=self.frameButtons)
        self.pushButtonAssignedApplicants.setMinimumSize(QtCore.QSize(170, 35))
        self.pushButtonAssignedApplicants.setMaximumSize(QtCore.QSize(170, 35))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButtonAssignedApplicants.setFont(font)
        self.pushButtonAssignedApplicants.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}")
        self.pushButtonAssignedApplicants.setObjectName("pushButtonAssignedApplicants")
        self.verticalLayout.addWidget(self.pushButtonAssignedApplicants)
        self.pushButtonInterviewedApplicants = QtWidgets.QPushButton(parent=self.frameButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonInterviewedApplicants.sizePolicy().hasHeightForWidth())
        self.pushButtonInterviewedApplicants.setSizePolicy(sizePolicy)
        self.pushButtonInterviewedApplicants.setMinimumSize(QtCore.QSize(170, 35))
        self.pushButtonInterviewedApplicants.setMaximumSize(QtCore.QSize(170, 35))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButtonInterviewedApplicants.setFont(font)
        self.pushButtonInterviewedApplicants.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}")
        self.pushButtonInterviewedApplicants.setObjectName("pushButtonInterviewedApplicants")
        self.verticalLayout.addWidget(self.pushButtonInterviewedApplicants)
        self.pushButtonBackMenu = QtWidgets.QPushButton(parent=self.frameButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBackMenu.sizePolicy().hasHeightForWidth())
        self.pushButtonBackMenu.setSizePolicy(sizePolicy)
        self.pushButtonBackMenu.setMinimumSize(QtCore.QSize(170, 35))
        self.pushButtonBackMenu.setMaximumSize(QtCore.QSize(170, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonBackMenu.setFont(font)
        self.pushButtonBackMenu.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}")
        self.pushButtonBackMenu.setObjectName("pushButtonBackMenu")
        self.verticalLayout.addWidget(self.pushButtonBackMenu)
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.frameButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonExit.sizePolicy().hasHeightForWidth())
        self.pushButtonExit.setSizePolicy(sizePolicy)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(170, 35))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(170, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.verticalLayout.addWidget(self.pushButtonExit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frameButtons, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelAreaKeeper2 = QtWidgets.QLabel(parent=FormInterviews)
        self.labelAreaKeeper2.setMinimumSize(QtCore.QSize(190, 10))
        self.labelAreaKeeper2.setMaximumSize(QtCore.QSize(190, 10))
        self.labelAreaKeeper2.setStyleSheet("QLabel {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.labelAreaKeeper2.setText("")
        self.labelAreaKeeper2.setObjectName("labelAreaKeeper2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelAreaKeeper2)
        self.labelInfo1 = QtWidgets.QLabel(parent=FormInterviews)
        self.labelInfo1.setEnabled(False)
        self.labelInfo1.setMinimumSize(QtCore.QSize(10, 10))
        self.labelInfo1.setMaximumSize(QtCore.QSize(10, 10))
        self.labelInfo1.setText("")
        self.labelInfo1.setObjectName("labelInfo1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.labelInfo1)
        self.verticalLayout_2.addLayout(self.formLayout)

        self.retranslateUi(FormInterviews)
        QtCore.QMetaObject.connectSlotsByName(FormInterviews)

    def retranslateUi(self, FormInterviews):
        _translate = QtCore.QCoreApplication.translate
        FormInterviews.setWindowTitle(_translate("FormInterviews", "INTERVIEWS PAGE"))
        self.labelMenu.setText(_translate("FormInterviews", "INTERVIEWS MENU"))
        self.lineEditSearch.setPlaceholderText(_translate("FormInterviews", "      Name or Surname"))
        self.pushButtonUnassignedApplicants.setText(_translate("FormInterviews", "Unassigned Apllicants"))
        self.pushButtonAssignedApplicants.setText(_translate("FormInterviews", "Assigned Applicants"))
        self.pushButtonInterviewedApplicants.setText(_translate("FormInterviews", "Interviewed Applicants"))
        self.pushButtonBackMenu.setText(_translate("FormInterviews", "Back Menu"))
        self.pushButtonExit.setText(_translate("FormInterviews", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormInterviews = QtWidgets.QWidget()
    ui = Ui_FormInterviews()
    ui.setupUi(FormInterviews)
    FormInterviews.show()
    sys.exit(app.exec())
