# Form implementation generated from reading ui file 'UI_Files/main_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 350)
        MainWindow.setMinimumSize(QtCore.QSize(350, 350))
        MainWindow.setMaximumSize(QtCore.QSize(350, 350))
        MainWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        MainWindow.setWindowTitle("LOGIN")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_Files\\pictures/logo_organization1.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.499773, y1:1, x2:0.5, y2:0.00568182, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"One value - border-radius: 100px;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonVIT1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonVIT1.setGeometry(QtCore.QRect(50, 130, 101, 61))
        self.pushButtonVIT1.setMouseTracking(True)
        self.pushButtonVIT1.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButtonVIT1.setStyleSheet("QPushButton {\n"
"    background-color: rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    border-top-left-radius: 15px;\n"
"    border-top-right-radius: 15px;\n"
"    border-bottom-left-radius: 0px;  /* Alt kenarları düz bırak */\n"
"    border-bottom-right-radius: 0px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButtonVIT1.setText("")
        self.pushButtonVIT1.setIcon(icon)
        self.pushButtonVIT1.setIconSize(QtCore.QSize(45, 60))
        self.pushButtonVIT1.setObjectName("pushButtonVIT1")
        self.labelSelect = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelSelect.setGeometry(QtCore.QRect(10, 20, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setUnderline(True)
        self.labelSelect.setFont(font)
        self.labelSelect.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.labelSelect.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.labelSelect.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelSelect.setObjectName("labelSelect")
        self.pushButtonVIT2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonVIT2.setGeometry(QtCore.QRect(50, 185, 101, 31))
        self.pushButtonVIT2.setMouseTracking(True)
        self.pushButtonVIT2.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButtonVIT2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 15px;  /* Alt kenarları düz bırak */\n"
"    border-bottom-right-radius: 15px;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.pushButtonVIT2.setObjectName("pushButtonVIT2")
        self.pushButtonOtherApp1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonOtherApp1.setGeometry(QtCore.QRect(200, 130, 101, 61))
        self.pushButtonOtherApp1.setMouseTracking(True)
        self.pushButtonOtherApp1.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButtonOtherApp1.setStyleSheet("QPushButton {\n"
"    background-color: rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    border-top-left-radius: 15px;\n"
"    border-top-right-radius: 15px;\n"
"    border-bottom-left-radius: 0px;  /* Alt kenarları düz bırak */\n"
"    border-bottom-right-radius: 0px;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.pushButtonOtherApp1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI_Files\\pictures/logo_other_app.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonOtherApp1.setIcon(icon1)
        self.pushButtonOtherApp1.setIconSize(QtCore.QSize(90, 90))
        self.pushButtonOtherApp1.setObjectName("pushButtonOtherApp1")
        self.pushButtonOtherApp2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonOtherApp2.setGeometry(QtCore.QRect(200, 185, 101, 31))
        self.pushButtonOtherApp2.setMouseTracking(True)
        self.pushButtonOtherApp2.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButtonOtherApp2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 15px;  /* Alt kenarları düz bırak */\n"
"    border-bottom-right-radius: 15px;\n"
"    padding: 10px;\n"
"}")
        self.pushButtonOtherApp2.setObjectName("pushButtonOtherApp2")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(120, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}")
        self.pushButtonExit.setObjectName("pushButtonExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.labelSelect.setText(_translate("MainWindow", "SELECT AN APP"))
        self.pushButtonVIT2.setText(_translate("MainWindow", "VIT"))
        self.pushButtonOtherApp2.setText(_translate("MainWindow", "APP"))
        self.pushButtonExit.setText(_translate("MainWindow", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
