# Form implementation generated from reading ui file 'UI_Files/management_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormManagement(object):
    def setupUi(self, FormManagement):
        FormManagement.setObjectName("FormManagement")
        FormManagement.resize(520, 613)
        font = QtGui.QFont()
        font.setBold(False)
        FormManagement.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_Files\\pictures/logo_organization1.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FormManagement.setWindowIcon(icon)
        FormManagement.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.499773, y1:1, x2:0.5, y2:0.00568182, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"\n"
"QToolTip { background-color: yellow; color: black; border: 1px solid black;}")
        self.centralwidget = QtWidgets.QWidget(parent=FormManagement)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonAddNewUser = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAddNewUser.setGeometry(QtCore.QRect(100, 210, 120, 120))
        self.pushButtonAddNewUser.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonAddNewUser.setMaximumSize(QtCore.QSize(120, 120))
        self.pushButtonAddNewUser.setStyleSheet("QPushButton {\n"
"    border-radius : 60px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"  border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonAddNewUser.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI_Files\\pictures/icon_add_new_user.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAddNewUser.setIcon(icon1)
        self.pushButtonAddNewUser.setIconSize(QtCore.QSize(160, 149))
        self.pushButtonAddNewUser.setObjectName("pushButtonAddNewUser")
        self.pushButtonBackMenu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBackMenu.setGeometry(QtCore.QRect(190, 480, 120, 61))
        self.pushButtonBackMenu.setMaximumSize(QtCore.QSize(141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButtonBackMenu.setFont(font)
        self.pushButtonBackMenu.setStyleSheet("QPushButton{\n"
"    border-radius : 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}\n"
"")
        self.pushButtonBackMenu.setIconSize(QtCore.QSize(120, 110))
        self.pushButtonBackMenu.setObjectName("pushButtonBackMenu")
        self.pushButtonUpdateDriveFolder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonUpdateDriveFolder.setGeometry(QtCore.QRect(280, 210, 120, 120))
        self.pushButtonUpdateDriveFolder.setMaximumSize(QtCore.QSize(120, 120))
        self.pushButtonUpdateDriveFolder.setStyleSheet("QPushButton{\n"
"    border-radius : 60px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}\n"
"\n"
"QPushButton:focus  {\n"
"  border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonUpdateDriveFolder.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("UI_Files\\pictures/icon_update_drive_folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonUpdateDriveFolder.setIcon(icon2)
        self.pushButtonUpdateDriveFolder.setIconSize(QtCore.QSize(110, 100))
        self.pushButtonUpdateDriveFolder.setObjectName("pushButtonUpdateDriveFolder")
        self.pushButtonUpdateDeadline = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonUpdateDeadline.setGeometry(QtCore.QRect(280, 340, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButtonUpdateDeadline.setFont(font)
        self.pushButtonUpdateDeadline.setStyleSheet("QPushButton{\n"
"    border-radius : 60px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}\n"
"\n"
"QPushButton:focus  {\n"
"  border: 2px solid rgb(162, 0, 0);\n"
"}\n"
"")
        self.pushButtonUpdateDeadline.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("UI_Files\\pictures/icon_update_deadline.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonUpdateDeadline.setIcon(icon3)
        self.pushButtonUpdateDeadline.setIconSize(QtCore.QSize(120, 110))
        self.pushButtonUpdateDeadline.setObjectName("pushButtonUpdateDeadline")
        self.labelLogo = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelLogo.setGeometry(QtCore.QRect(18, 25, 90, 90))
        self.labelLogo.setMinimumSize(QtCore.QSize(0, 0))
        self.labelLogo.setMaximumSize(QtCore.QSize(90, 90))
        self.labelLogo.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("UI_Files\\pictures/logo_organization1.ico"))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setObjectName("labelLogo")
        self.labelWerhere = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelWerhere.setGeometry(QtCore.QRect(121, 25, 380, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWerhere.sizePolicy().hasHeightForWidth())
        self.labelWerhere.setSizePolicy(sizePolicy)
        self.labelWerhere.setMinimumSize(QtCore.QSize(0, 80))
        self.labelWerhere.setMaximumSize(QtCore.QSize(380, 80))
        self.labelWerhere.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelWerhere.setText("")
        self.labelWerhere.setPixmap(QtGui.QPixmap("UI_Files\\pictures/logo_organization2.png"))
        self.labelWerhere.setScaledContents(True)
        self.labelWerhere.setObjectName("labelWerhere")
        self.labelManagementMenu = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelManagementMenu.setGeometry(QtCore.QRect(11, 131, 511, 58))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setUnderline(True)
        self.labelManagementMenu.setFont(font)
        self.labelManagementMenu.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"QLabel {\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"}\n"
"")
        self.labelManagementMenu.setScaledContents(True)
        self.labelManagementMenu.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelManagementMenu.setObjectName("labelManagementMenu")
        self.pushButtonResetUserPassword = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonResetUserPassword.setGeometry(QtCore.QRect(100, 340, 120, 120))
        self.pushButtonResetUserPassword.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonResetUserPassword.setMaximumSize(QtCore.QSize(120, 120))
        self.pushButtonResetUserPassword.setStyleSheet("QPushButton {\n"
"    border-radius : 60px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(255, 80, 0);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"  border: 2px solid rgb(162, 0, 0);\n"
"}")
        self.pushButtonResetUserPassword.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("UI_Files\\pictures/icon_change_user_password.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonResetUserPassword.setIcon(icon4)
        self.pushButtonResetUserPassword.setIconSize(QtCore.QSize(160, 149))
        self.pushButtonResetUserPassword.setObjectName("pushButtonResetUserPassword")
        FormManagement.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=FormManagement)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 22))
        self.menubar.setObjectName("menubar")
        self.menuActions = QtWidgets.QMenu(parent=self.menubar)
        self.menuActions.setObjectName("menuActions")
        self.menuAbout = QtWidgets.QMenu(parent=self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        FormManagement.setMenuBar(self.menubar)
        self.actionAdd_New_User = QtGui.QAction(parent=FormManagement)
        self.actionAdd_New_User.setObjectName("actionAdd_New_User")
        self.actionUpdate_Google_Drive_Folder = QtGui.QAction(parent=FormManagement)
        self.actionUpdate_Google_Drive_Folder.setObjectName("actionUpdate_Google_Drive_Folder")
        self.actionUpdate_Project_Deadline = QtGui.QAction(parent=FormManagement)
        self.actionUpdate_Project_Deadline.setObjectName("actionUpdate_Project_Deadline")
        self.actionBack_Menu = QtGui.QAction(parent=FormManagement)
        self.actionBack_Menu.setObjectName("actionBack_Menu")
        self.actionExit = QtGui.QAction(parent=FormManagement)
        self.actionExit.setObjectName("actionExit")
        self.actionReset_Users_Passwords = QtGui.QAction(parent=FormManagement)
        self.actionReset_Users_Passwords.setObjectName("actionReset_Users_Passwords")
        self.actionLogs = QtGui.QAction(parent=FormManagement)
        self.actionLogs.setObjectName("actionLogs")
        self.actionAbout_Coder = QtGui.QAction(parent=FormManagement)
        self.actionAbout_Coder.setObjectName("actionAbout_Coder")
        self.menuActions.addAction(self.actionAdd_New_User)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionReset_Users_Passwords)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionUpdate_Google_Drive_Folder)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionUpdate_Project_Deadline)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionLogs)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionBack_Menu)
        self.menuAbout.addAction(self.actionAbout_Coder)
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(FormManagement)
        QtCore.QMetaObject.connectSlotsByName(FormManagement)
        FormManagement.setTabOrder(self.pushButtonBackMenu, self.pushButtonAddNewUser)
        FormManagement.setTabOrder(self.pushButtonAddNewUser, self.pushButtonResetUserPassword)
        FormManagement.setTabOrder(self.pushButtonResetUserPassword, self.pushButtonUpdateDriveFolder)
        FormManagement.setTabOrder(self.pushButtonUpdateDriveFolder, self.pushButtonUpdateDeadline)

    def retranslateUi(self, FormManagement):
        _translate = QtCore.QCoreApplication.translate
        FormManagement.setWindowTitle(_translate("FormManagement", "Management Menu"))
        self.pushButtonBackMenu.setText(_translate("FormManagement", "Back Menu"))
        self.labelManagementMenu.setText(_translate("FormManagement", "Management Menu"))
        self.menuActions.setTitle(_translate("FormManagement", "Actions"))
        self.menuAbout.setTitle(_translate("FormManagement", "About"))
        self.actionAdd_New_User.setText(_translate("FormManagement", "Add New User"))
        self.actionUpdate_Google_Drive_Folder.setText(_translate("FormManagement", "Update Google Drive Folder"))
        self.actionUpdate_Project_Deadline.setText(_translate("FormManagement", "Update Project Deadline"))
        self.actionBack_Menu.setText(_translate("FormManagement", "Back Menu"))
        self.actionExit.setText(_translate("FormManagement", "Exit"))
        self.actionReset_Users_Passwords.setText(_translate("FormManagement", "Change Users Passwords"))
        self.actionLogs.setText(_translate("FormManagement", "Logs"))
        self.actionAbout_Coder.setText(_translate("FormManagement", "About Coder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormManagement = QtWidgets.QMainWindow()
    ui = Ui_FormManagement()
    ui.setupUi(FormManagement)
    FormManagement.show()
    sys.exit(app.exec())
